--!strict

return table.freeze({
	Ambient = table.freeze({
		backyard = table.freeze({ AssetId = 9112758786, Volume = 0.075, PlaybackSpeed = 1.00 }),
		downtown = table.freeze({ AssetId = 9112757705, Volume = 0.085, PlaybackSpeed = 1.00 }),
		industrial = table.freeze({ AssetId = 9112761348, Volume = 0.080, PlaybackSpeed = 0.98 }),
		airport = table.freeze({ AssetId = 9112758786, Volume = 0.060, PlaybackSpeed = 0.96 }),
		megacity = table.freeze({ AssetId = 9112761135, Volume = 0.070, PlaybackSpeed = 0.96 }),
	}),
	AmbientFadeSeconds = 1.35,
	AmbientMasterVolume = 0.72,
})
