--!strict

return table.freeze({
	table.freeze({ Name = "State", Kind = "Event" }),
	table.freeze({ Name = "OrbitCollect", Kind = "Event" }),
	table.freeze({ Name = "CollapseFx", Kind = "Event" }),
	table.freeze({ Name = "Action", Kind = "Event" }),
	table.freeze({ Name = "QueryState", Kind = "Function" }),
	table.freeze({ Name = "CosmeticAction", Kind = "Event" }),
	table.freeze({ Name = "ShopAction", Kind = "Event" }),
	table.freeze({ Name = "LeaderboardQuery", Kind = "Function" }),
})
